<?php

declare(strict_types=1);

namespace hypeJunction\Maps\Tests\Unit;

use PHPUnit\Framework\TestCase;

/**
 * Auto-generated migration regression guard for plugin "hypemaps".
 *
 * Generated by elgg-test-writer. Do not edit by hand — re-run the scaffold
 * (bin/scaffold-smoke-tests.sh --target-version=elgg7).
 *
 * TESTS-FIRST CONTRACT
 * --------------------
 * This test asserts that EVERY statically-detectable failure class from
 * skills/elgg-migrate/references/migration-failure-catalog.md is ABSENT for
 * the target major (Elgg 7.x). Run it BEFORE touching any
 * plugin code:
 *
 *   - BEFORE migration → RED   (the un-migrated plugin still trips the classes)
 *   - AFTER  migration → GREEN (every class is fixed)
 *
 * That RED→GREEN transition is the proof the migration actually landed — not a
 * "it still activates" smoke pass, which the catalog shows repeatedly missing
 * page-render and boot fatals.
 *
 * WHY STATIC (no Elgg boot)
 * -------------------------
 * Most catalog classes fatal at class-load or page-render on the target
 * version, so a booted test crashes before it can assert. The signature has to
 * be caught in the source. Mirrors the engine-side detectors
 * (elgg-migrate/bin/scan-frontend-residue.sh, PostMigrationVerifier,
 * removed-functions.json, changed-class-contracts.json) so the guard travels
 * with the plugin and fails its own CI. Keep the embedded maps in lock-step
 * with those files.
 *
 * Runtime confirmation (real activation + route 200s) is the job of the
 * post-migration SmokeTest and the LLM-driven route/render battery. This file
 * is the deterministic, pre-migration RED gate.
 *
 * Catalog classes covered (target-gated):
 *   FC-*x*x removed symbols ...... testNoRemovedSymbols
 *   FC-3x4x-01 forbidden files ... testNoForbiddenBootstrapFiles
 *   FC-2x3x-02 start.php present .. testStartPhpPresentOn3x
 *   FC-3x4x-10 lowercase id ...... testNoCamelCasePluginIdCallsites
 *   FC-3x4x-09 hook/event mixup .. testNoHookEventConfusion
 *   FC-5x6x-03 Seed shape ........ testSeedSubclassShape
 *   FC-5x6x-04 Batch shape ....... testNoRemovedClassContracts / testUpgradeBatchShape
 *   FC-5x6x-01 Hook removed ...... testNoRemovedClassContracts
 *   FC-4x5x-01 add_translation ... testNoLegacyLanguageFiles
 *   FC-ALL-01  unserialize RCE ... testNoUnsafeUnserialize
 *   FC-ALL-05  route:rewrite@init  testNoRouteRewriteAtInit
 *   FC-ALL-06  ::class in manifest  testManifestUsesStringLiterals
 *   bug-007/013 sig-incompat ..... testNoIncompatibleCoreOverrides
 *   FC-6x7x-03 menu ->add() ...... testMenuRegisterReturnsArray
 *   FC-6x7x-05 css orphaned ...... testNoOrphanedCssElementViews
 */
final class MigrationRegressionTest extends TestCase
{
    /** Target Elgg major this suite guards (filled in at scaffold time). */
    private const TARGET_MAJOR = 7;

    /**
     * Global functions REMOVED at each major, keyed by the major that removed
     * them. Treated CUMULATIVELY: a function removed at 4 is still removed at 7.
     * Mirror of skills/elgg-migrate/references/removed-functions.json (call
     * forms only — bare constants and static-method forms are handled below).
     *
     * @var array<int, list<string>>
     */
    private const REMOVED_FUNCTIONS = [
        3 => [
            'elgg_get_metastring_id',
            '_elgg_entities_get_metastrings_options',
        ],
        4 => [
            'elgg_register_css',
            'elgg_load_css',
            'elgg_format_attributes',
            'access_get_show_hidden_status',
            'create_metadata',
            'update_metadata',
            'elgg_flush_simplecache',
        ],
        5 => [
            'add_translation',
            'get_default_access',
            'get_current_language',
            'check_entity_relationship',
        ],
        6 => [
            'elgg_trigger_plugin_hook',
            'elgg_register_plugin_hook_handler',
            'elgg_unregister_plugin_hook_handler',
            'elgg_clear_plugin_hook_handlers',
            'register_error',
            'system_message',
            'forward',
            'elgg_redirect',
            'current_page_url',
            '_elgg_rmdir',
            'elgg_require_js',
            'elgg_load_js',
            'elgg_define_js',
            'elgg_unregister_css',
            'elgg_flush_caches',
            'elgg_get_version',
            'elgg_instanceof',
            'elgg_set_ignore_access',
            'elgg_view_menu_item',
            'elgg_pop_breadcrumb',
            'elgg_set_plugin_setting',
            'elgg_unset_plugin_setting',
            'elgg_set_plugin_user_setting',
            'elgg_unset_plugin_user_setting',
            'elgg_delete_metadata_by_id',
            'elgg_add_subscription',
            'elgg_group_gatekeeper',
            'elgg_get_group_tool_options',
            'elgg_get_file_simple_type',
            'elgg_get_registered_tag_metadata_names',
            'elgg_list_views',
            'elgg_register_admin_menu_item',
            'elgg_strrchr',
            'elgg_strripos',
            'elgg_set_view_location',
            'elgg_disable_annotations',
            'elgg_enable_annotations',
            '_elgg_html_decode',
            '_elgg_get_display_query',
            '_elgg_get_access_where_sql',
            '_elgg_admin_add_plugin_settings_menu',
        ],
        7 => [
            'elgg_is_admin_user',
            'elgg_get_logged_in_user',
            'elgg_new_entity',
            'elgg_get_entities_from_relationship',
            'elgg_is_registered_viewtype',
            'elgg_get_registered_entity_types',
            'elgg_geocode_location',
            'elgg_reset_system_cache',
        ],
    ];

    /**
     * Bare global constants removed at a major (no `(` → the call-shaped scan
     * misses them). Keyed cumulatively like REMOVED_FUNCTIONS.
     *
     * @var array<int, list<string>>
     */
    private const REMOVED_CONSTANTS = [
        7 => ['ELGG_CACHE_PERSISTENT'],
    ];

    /**
     * Core types whose KIND changed so a plugin's use/new/implements fatals at
     * or beyond the boundary. Mirror of changed-class-contracts.json. Each row:
     * [needle regex, forbidden keyword regex, human message].
     *
     * @var array<int, list<array{0:string,1:string,2:string}>>
     */
    private const CHANGED_CONTRACTS = [
        4 => [
            ['Elgg\\\\Di\\\\ServiceFacade', 'use', 'Elgg\\Di\\ServiceFacade trait was removed in 4.x — register via DI\\create() in elgg-services.php'],
            ['Elgg\\\\Notifications\\\\NotificationEvent', 'new', 'Elgg\\Notifications\\NotificationEvent is an interface in 4.x — instantiate SubscriptionNotificationEvent / InstantNotificationEvent'],
        ],
        6 => [
            ['Elgg\\\\Upgrade\\\\Batch', 'implements', 'Elgg\\Upgrade\\Batch became an abstract class in 6.x — extends \\Elgg\\Upgrade\\AsynchronousUpgrade instead of implements Batch'],
            ['Elgg\\\\Hook', 'use', 'Elgg\\Hook was removed in 6.x — use Elgg\\Event; and type-hint \\Elgg\\Event $event'],
        ],
    ];

    /** Canonical Elgg core method signatures (param "type $name" list, defaults stripped). */
    private const CORE_SIG = [
        'canComment'          => 'int $user_guid',
        'canWriteToContainer' => 'int $user_guid, string $type, string $subtype',
        'canEdit'             => 'int $user_guid',
        'canDelete'           => 'int $user_guid',
        'canAnnotate'         => 'int $user_guid, string $annotation_name',
    ];

    /* ---------------------------------------------------------------- helpers */

    private static function pluginRoot(): string
    {
        $dir = __DIR__;
        for ($i = 0; $i < 6; $i++) {
            if (is_file($dir . '/elgg-plugin.php') || is_file($dir . '/manifest.xml') || is_file($dir . '/composer.json')) {
                return $dir;
            }
            $dir = \dirname($dir);
        }
        return \dirname(__DIR__);
    }

    /** @return list<string> files with $ext under $sub (relative dir); vendor dirs skipped */
    private static function files(string $sub, string $ext): array
    {
        $base = self::pluginRoot() . '/' . ltrim($sub, '/');
        if (!is_dir($base)) {
            return [];
        }
        $out = [];
        $it = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($base, \FilesystemIterator::SKIP_DOTS));
        foreach ($it as $f) {
            $path = $f->getPathname();
            if (preg_match('#/(vendor|vendors|bower_components|node_modules)/#', $path)) {
                continue;
            }
            if (str_ends_with($path, '.' . $ext)) {
                $out[] = $path;
            }
        }
        return $out;
    }

    /** @return list<string> cumulative removed function names for the target major */
    private static function cumulative(array $byMajor): array
    {
        $out = [];
        foreach ($byMajor as $major => $names) {
            if ((int) $major <= self::TARGET_MAJOR) {
                $out = array_merge($out, $names);
            }
        }
        return $out;
    }

    private static function normParams(string $raw): string
    {
        $tokens = [];
        foreach (explode(',', $raw) as $p) {
            $p = preg_replace('/=.*$/', '', $p);
            $p = trim(preg_replace('/\s+/', ' ', $p));
            if ($p !== '') {
                $tokens[] = $p;
            }
        }
        return implode(', ', $tokens);
    }

    private static function manifestSource(): string
    {
        $manifest = self::pluginRoot() . '/elgg-plugin.php';
        return is_file($manifest) ? (string) file_get_contents($manifest) : '';
    }

    /* ---------------------------------------------------------------- removed symbols */

    public function testNoRemovedSymbols(): void
    {
        $removed = self::cumulative(self::REMOVED_FUNCTIONS);
        if ($removed === []) {
            $this->assertTrue(true);
            return;
        }
        $alt = implode('|', array_map(static fn (string $n): string => preg_quote($n, '#'), $removed));
        // call form, not a method call ( ->foo, ::foo ) and not a definition
        $re = '#(?<![\w>$:\\\\])(' . $alt . ')\s*\(#';

        $violations = [];
        foreach (self::files('', 'php') as $file) {
            if (str_contains($file, '/tests/')) {
                continue;
            }
            foreach (explode("\n", (string) file_get_contents($file)) as $n => $line) {
                if (preg_match_all($re, $line, $m)) {
                    foreach ($m[1] as $sym) {
                        $violations[] = sprintf('%s:%d %s() — removed at/before Elgg %d.x', basename($file), $n + 1, $sym, self::TARGET_MAJOR);
                    }
                }
            }
        }
        $this->assertSame([], $violations, "Calls to removed core functions fatal on Elgg " . self::TARGET_MAJOR . ".x:\n" . implode("\n", $violations));
    }

    public function testNoRemovedConstants(): void
    {
        $removed = self::cumulative(self::REMOVED_CONSTANTS);
        if ($removed === []) {
            $this->assertTrue(true);
            return;
        }
        $alt = implode('|', array_map(static fn (string $n): string => preg_quote($n, '#'), $removed));
        $re = '#(?<![\w\\\\])(' . $alt . ')\b#';

        $violations = [];
        foreach (self::files('', 'php') as $file) {
            if (str_contains($file, '/tests/')) {
                continue;
            }
            if (preg_match_all($re, (string) file_get_contents($file), $m)) {
                foreach (array_unique($m[1]) as $c) {
                    $violations[] = basename($file) . ": {$c} removed on Elgg " . self::TARGET_MAJOR . '.x';
                }
            }
        }
        $this->assertSame([], $violations, "Use of removed core constants:\n" . implode("\n", $violations));
    }

    public function testNoRemovedStaticMimeType(): void
    {
        if (self::TARGET_MAJOR < 4) {
            $this->assertTrue(true);
            return;
        }
        $violations = [];
        foreach (self::files('', 'php') as $file) {
            if (str_contains($file, '/tests/')) {
                continue;
            }
            if (preg_match('/(ElggFile::|->)detectMimeType\s*\(/', (string) file_get_contents($file))) {
                $violations[] = basename($file) . ': detectMimeType() removed in 4.x — use mime_content_type($path) guarded by is_file()';
            }
        }
        $this->assertSame([], $violations, "Calls to removed ElggFile::detectMimeType:\n" . implode("\n", $violations));
    }

    /* ---------------------------------------------------------------- changed class contracts */

    public function testNoRemovedClassContracts(): void
    {
        $rows = [];
        foreach (self::CHANGED_CONTRACTS as $major => $entries) {
            if ((int) $major <= self::TARGET_MAJOR) {
                $rows = array_merge($rows, $entries);
            }
        }
        if ($rows === []) {
            $this->assertTrue(true);
            return;
        }
        $violations = [];
        foreach (self::files('', 'php') as $file) {
            if (str_contains($file, '/tests/')) {
                continue;
            }
            foreach (explode("\n", (string) file_get_contents($file)) as $n => $line) {
                foreach ($rows as [$needle, $keyword, $msg]) {
                    if (preg_match('/' . $needle . '\b/', $line) && preg_match('/\b' . $keyword . '\b/', $line)) {
                        $violations[] = sprintf('%s:%d — %s', basename($file), $n + 1, $msg);
                    }
                }
            }
        }
        $this->assertSame([], $violations, "Changed core-type contracts fatal on boot:\n" . implode("\n", $violations));
    }

    /* ---------------------------------------------------------------- forbidden / required files */

    public function testNoForbiddenBootstrapFiles(): void
    {
        if (self::TARGET_MAJOR < 4) {
            $this->assertTrue(true);
            return;
        }
        $root = self::pluginRoot();
        $violations = [];
        foreach (['start.php', 'activate.php', 'deactivate.php'] as $forbidden) {
            if (is_file($root . '/' . $forbidden)) {
                $violations[] = "{$forbidden} must be deleted for Elgg 4.x+ (plugin is rejected on activation)";
            }
        }
        $this->assertSame([], $violations, "Forbidden bootstrap files present:\n" . implode("\n", $violations));
    }

    public function testStartPhpPresentOn3x(): void
    {
        if (self::TARGET_MAJOR !== 3) {
            $this->assertTrue(true);
            return;
        }
        $root = self::pluginRoot();
        // 3.x still requires start.php (returning a closure) alongside elgg-plugin.php.
        if (is_file($root . '/elgg-plugin.php')) {
            $this->assertFileExists($root . '/start.php', 'Elgg 3.x plugins keep start.php — do not delete it until the 3.x→4.x step');
        } else {
            $this->assertTrue(true);
        }
    }

    /* ---------------------------------------------------------------- lowercase plugin id */

    public function testNoCamelCasePluginIdCallsites(): void
    {
        if (self::TARGET_MAJOR < 4) {
            $this->assertTrue(true);
            return;
        }
        $violations = [];
        foreach (self::files('', 'php') as $file) {
            if (str_contains($file, '/tests/')) {
                continue;
            }
            $src = (string) file_get_contents($file);
            // NOTE: the argument scan is bounded by the call's own closing paren
            // ([^;)]) — an unbounded [^;] bled past the call into unrelated array
            // literals (e.g. 'method' => 'GET') and produced false positives.
            if (preg_match_all('/elgg_get_plugin_(?:from_id|setting|user_setting)\s*\([^;)]*?[\'"]([A-Za-z0-9_]*[A-Z][A-Za-z0-9_]*)[\'"]/', $src, $m)) {
                foreach (array_unique($m[1]) as $id) {
                    $violations[] = basename($file) . ": plugin id '{$id}' has uppercase — 4.x lowercases ids, callsite silently returns false";
                }
            }
        }
        $this->assertSame([], $violations, "camelCase plugin-id callsites resolve to false on Elgg 4.x+:\n" . implode("\n", $violations));
    }

    /* ---------------------------------------------------------------- hook/event confusion */

    public function testNoHookEventConfusion(): void
    {
        if (self::TARGET_MAJOR !== 4) {
            $this->assertTrue(true);
            return;
        }
        // In 4.x, view/register/route/prepare are HOOKS, not events. Flag them
        // under the 'events' key of elgg-plugin.php.
        $src = self::manifestSource();
        if ($src === '' || !preg_match("/['\"]events['\"]\s*=>\s*\[(.*?)\n\s*\],/s", $src, $block)) {
            $this->assertTrue(true);
            return;
        }
        $violations = [];
        foreach (['view', 'register', 'route', 'prepare'] as $hookName) {
            if (preg_match('/[\'"]' . $hookName . '[\'"]\s*=>/', $block[1])) {
                $violations[] = "'{$hookName}' is a HOOK in 4.x but is registered under the 'events' key of elgg-plugin.php";
            }
        }
        $this->assertSame([], $violations, "Hook/event confusion in elgg-plugin.php:\n" . implode("\n", $violations));
    }

    /* ---------------------------------------------------------------- Seed / Batch shape */

    public function testSeedSubclassShape(): void
    {
        if (self::TARGET_MAJOR < 6) {
            $this->assertTrue(true);
            return;
        }
        $violations = [];
        foreach (self::files('classes', 'php') as $file) {
            $src = (string) file_get_contents($file);
            if (!preg_match('/\bextends\s+\\\\?(?:Elgg\\\\Database\\\\Seeds\\\\)?Seed\b/', $src)) {
                continue;
            }
            $hasType = (bool) preg_match('/function\s+getType\s*\(/', $src);
            $hasCount = (bool) preg_match('/function\s+getCountOptions\s*\(/', $src);
            if (!$hasType || !$hasCount) {
                $missing = [];
                if (!$hasType) {
                    $missing[] = 'getType()';
                }
                if (!$hasCount) {
                    $missing[] = 'getCountOptions()';
                }
                $violations[] = basename($file) . ': Seed subclass missing ' . implode(' + ', $missing) . ' (abstract since 6.1 — fatals on every page load)';
            }
        }
        $this->assertSame([], $violations, "Incomplete Seed subclass shape on Elgg 6.x+:\n" . implode("\n", $violations));
    }

    public function testUpgradeBatchShape(): void
    {
        if (self::TARGET_MAJOR < 6) {
            $this->assertTrue(true);
            return;
        }
        $violations = [];
        foreach (self::files('classes', 'php') as $file) {
            $src = (string) file_get_contents($file);
            if (preg_match('/\bimplements\b[^;{]*\bBatch\b/', $src)) {
                $violations[] = basename($file) . ': `implements Batch` fatals in 6.x — extends \\Elgg\\Upgrade\\AsynchronousUpgrade';
            }
        }
        $this->assertSame([], $violations, "Upgrade Batch shape wrong on Elgg 6.x+:\n" . implode("\n", $violations));
    }

    /* ---------------------------------------------------------------- language files */

    public function testNoLegacyLanguageFiles(): void
    {
        if (self::TARGET_MAJOR < 5) {
            $this->assertTrue(true);
            return;
        }
        $violations = [];
        foreach (self::files('languages', 'php') as $file) {
            if (preg_match('/(^|[^A-Za-z_])add_translation\s*\(/m', (string) file_get_contents($file))) {
                $violations[] = basename($file) . ': add_translation() removed in 5.0 — return the array directly';
            }
        }
        $this->assertSame([], $violations, "Legacy language files fatal at boot on Elgg 5.x+:\n" . implode("\n", $violations));
    }

    /* ---------------------------------------------------------------- security (all versions) */

    public function testNoUnsafeUnserialize(): void
    {
        $violations = [];
        foreach (self::files('', 'php') as $file) {
            if (str_contains($file, '/tests/')) {
                continue;
            }
            foreach (explode("\n", (string) file_get_contents($file)) as $n => $line) {
                if (preg_match('/(?<![\w>$:\\\\])unserialize\s*\(/', $line) && !str_contains($line, 'allowed_classes')) {
                    $violations[] = basename($file) . ':' . ($n + 1) . ' unserialize() without allowed_classes => false (PHP object-injection RCE)';
                }
            }
        }
        $this->assertSame([], $violations, "Unsafe unserialize():\n" . implode("\n", $violations));
    }

    /* ---------------------------------------------------------------- boot-time timing / manifest */

    public function testNoRouteRewriteAtInit(): void
    {
        // route:rewrite fires at boot, BEFORE init. Registering it via the
        // elgg-plugin.php 'events' key (i.e. at init) is too late → site-wide 404.
        $src = self::manifestSource();
        if ($src === '') {
            $this->assertTrue(true);
            return;
        }
        $this->assertDoesNotMatchRegularExpression(
            "/['\"]route:rewrite['\"]\s*=>/",
            $src,
            'route:rewrite registered in elgg-plugin.php fires at init (too late) — register it in Bootstrap::boot()',
        );
    }

    public function testManifestUsesStringLiterals(): void
    {
        // elgg-plugin.php is parsed before the classes/ autoloader is wired, so
        // MyClass::SUBTYPE / \Ns\Class::class in the entities block fatal.
        $src = self::manifestSource();
        if ($src === '' || !preg_match("/['\"]entities['\"]\s*=>\s*\[(.*)\n\s*\],/sU", $src, $block)) {
            $this->assertTrue(true);
            return;
        }
        $violations = [];
        if (preg_match('/[\'"](?:class|subtype)[\'"]\s*=>\s*[\\\\\w]+::(?:class|[A-Z_]+)\b/', $block[1])) {
            $violations[] = 'entities block uses ClassName::class / ::CONST — use string literals (autoloader not wired at manifest parse time)';
        }
        $this->assertSame([], $violations, "Non-literal class/subtype in elgg-plugin.php entities block:\n" . implode("\n", $violations));
    }

    /* ---------------------------------------------------------------- entity-subclass signatures */

    public function testNoIncompatibleCoreOverrides(): void
    {
        if (self::TARGET_MAJOR < 4) {
            $this->assertTrue(true);
            return;
        }
        $violations = [];
        foreach (self::files('classes', 'php') as $file) {
            $src = (string) file_get_contents($file);
            if (!preg_match('/extends\s+\\\\?(ElggEntity|ElggObject|ElggComment|ElggGroup|ElggUser|ElggSite)\b/', $src)) {
                continue;
            }
            foreach (self::CORE_SIG as $method => $want) {
                if (!preg_match('/function\s+' . $method . '\s*\(([^)]*)\)/', $src, $m)) {
                    continue;
                }
                $got = self::normParams($m[1]);
                if ($got !== $want) {
                    $violations[] = sprintf('%s: %s(%s) — core wants %s(%s)', basename($file), $method, $got, $method, $want);
                }
            }
        }
        $this->assertSame([], $violations, "Incompatible core-method override(s) fatal at class load:\n" . implode("\n", $violations));
    }

    /* ---------------------------------------------------------------- menu register value (7.x) */

    public function testMenuRegisterReturnsArray(): void
    {
        if (self::TARGET_MAJOR < 7) {
            $this->assertTrue(true);
            return;
        }
        // In 7.x a register/menu handler's value is a plain array — $return->add()
        // / $menu->add() fatals. Look for ->add( on a var used as a menu return.
        $violations = [];
        foreach (array_merge(self::files('classes', 'php'), self::files('lib', 'php')) as $file) {
            $src = (string) file_get_contents($file);
            if (!preg_match('/register[\'"]?\s*,\s*[\'"]menu:|register:menu|MenuItems|ElggMenuItem/', $src)) {
                continue;
            }
            if (preg_match('/\$(?:return|menu|result)\s*->\s*add\s*\(/', $src)) {
                $violations[] = basename($file) . ': $return->add() in a menu handler fatals on 7.x — use $return[] = \\ElggMenuItem::factory([...]);';
            }
        }
        $this->assertSame([], $violations, "Menu register handler uses ->add() (array in 7.x):\n" . implode("\n", $violations));
    }

    /* ---------------------------------------------------------------- css relocation (7.x) */

    public function testNoOrphanedCssElementViews(): void
    {
        if (self::TARGET_MAJOR < 7) {
            $this->assertTrue(true);
            return;
        }
        $root = self::pluginRoot();
        $dir = $root . '/views/default/css/elements';
        if (!is_dir($dir)) {
            $this->assertTrue(true);
            return;
        }
        $allPhp = '';
        foreach (self::files('', 'php') as $f) {
            $allPhp .= (string) file_get_contents($f);
        }
        $violations = [];
        foreach (glob($dir . '/*.css') ?: [] as $css) {
            $base = basename($css);
            $stem = substr($base, 0, -4);
            if (is_file($root . '/views/default/elements/' . $base)) {
                continue;
            }
            if (str_contains($allPhp, 'css/elements/' . $stem)) {
                continue;
            }
            $violations[] = "css/elements/{$base} has no relocated twin and is not loaded explicitly → never loads on Elgg 7.x";
        }
        $this->assertSame([], $violations, "Orphaned css/elements overrides:\n" . implode("\n", $violations));
    }
}
